# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 276)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(570, 10, 91, 124))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ConnectButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ConnectButton.setObjectName("ConnectButton")
        self.verticalLayout.addWidget(self.ConnectButton)
        self.SettingsButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SettingsButton.setObjectName("SettingsButton")
        self.verticalLayout.addWidget(self.SettingsButton)
        self.RainbowButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RainbowButton.setEnabled(False)
        self.RainbowButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));")
        self.RainbowButton.setCheckable(False)
        self.RainbowButton.setFlat(False)
        self.RainbowButton.setObjectName("RainbowButton")
        self.verticalLayout.addWidget(self.RainbowButton)
        self.MoreButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.MoreButton.setDefault(False)
        self.MoreButton.setFlat(False)
        self.MoreButton.setObjectName("MoreButton")
        self.verticalLayout.addWidget(self.MoreButton)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 60, 551, 95))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LabelR = QtWidgets.QLabel(self.formLayoutWidget)
        self.LabelR.setObjectName("LabelR")
        self.verticalLayout_3.addWidget(self.LabelR)
        self.LabelG = QtWidgets.QLabel(self.formLayoutWidget)
        self.LabelG.setObjectName("LabelG")
        self.verticalLayout_3.addWidget(self.LabelG)
        self.LabelB = QtWidgets.QLabel(self.formLayoutWidget)
        self.LabelB.setObjectName("LabelB")
        self.verticalLayout_3.addWidget(self.LabelB)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SliderR = QtWidgets.QSlider(self.formLayoutWidget)
        self.SliderR.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderR.sizePolicy().hasHeightForWidth())
        self.SliderR.setSizePolicy(sizePolicy)
        self.SliderR.setMaximum(255)
        self.SliderR.setOrientation(QtCore.Qt.Horizontal)
        self.SliderR.setObjectName("SliderR")
        self.verticalLayout_2.addWidget(self.SliderR)
        self.SliderG = QtWidgets.QSlider(self.formLayoutWidget)
        self.SliderG.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderG.sizePolicy().hasHeightForWidth())
        self.SliderG.setSizePolicy(sizePolicy)
        self.SliderG.setMaximum(255)
        self.SliderG.setOrientation(QtCore.Qt.Horizontal)
        self.SliderG.setObjectName("SliderG")
        self.verticalLayout_2.addWidget(self.SliderG)
        self.SliderB = QtWidgets.QSlider(self.formLayoutWidget)
        self.SliderB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderB.sizePolicy().hasHeightForWidth())
        self.SliderB.setSizePolicy(sizePolicy)
        self.SliderB.setMaximum(255)
        self.SliderB.setOrientation(QtCore.Qt.Horizontal)
        self.SliderB.setObjectName("SliderB")
        self.verticalLayout_2.addWidget(self.SliderB)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 160, 551, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.SliderH = QtWidgets.QSlider(self.formLayoutWidget_2)
        self.SliderH.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderH.sizePolicy().hasHeightForWidth())
        self.SliderH.setSizePolicy(sizePolicy)
        self.SliderH.setMaximum(1535)
        self.SliderH.setOrientation(QtCore.Qt.Horizontal)
        self.SliderH.setObjectName("SliderH")
        self.verticalLayout_6.addWidget(self.SliderH)
        self.SliderS = QtWidgets.QSlider(self.formLayoutWidget_2)
        self.SliderS.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderS.sizePolicy().hasHeightForWidth())
        self.SliderS.setSizePolicy(sizePolicy)
        self.SliderS.setMaximum(255)
        self.SliderS.setOrientation(QtCore.Qt.Horizontal)
        self.SliderS.setObjectName("SliderS")
        self.verticalLayout_6.addWidget(self.SliderS)
        self.SliderV = QtWidgets.QSlider(self.formLayoutWidget_2)
        self.SliderV.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SliderV.sizePolicy().hasHeightForWidth())
        self.SliderV.setSizePolicy(sizePolicy)
        self.SliderV.setMaximum(255)
        self.SliderV.setOrientation(QtCore.Qt.Horizontal)
        self.SliderV.setObjectName("SliderV")
        self.verticalLayout_6.addWidget(self.SliderV)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LabelH = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.LabelH.setObjectName("LabelH")
        self.verticalLayout_7.addWidget(self.LabelH)
        self.LabelS = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.LabelS.setObjectName("LabelS")
        self.verticalLayout_7.addWidget(self.LabelS)
        self.LabelV = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.LabelV.setObjectName("LabelV")
        self.verticalLayout_7.addWidget(self.LabelV)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_7)
        self.LocalColor = QtWidgets.QLabel(Dialog)
        self.LocalColor.setGeometry(QtCore.QRect(570, 140, 91, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.LocalColor.setFont(font)
        self.LocalColor.setAutoFillBackground(False)
        self.LocalColor.setStyleSheet("background-color: rgb(0,0,0);\n"
"color: rgb(255, 255, 255);")
        self.LocalColor.setAlignment(QtCore.Qt.AlignCenter)
        self.LocalColor.setObjectName("LocalColor")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 551, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.IPLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IPLine.sizePolicy().hasHeightForWidth())
        self.IPLine.setSizePolicy(sizePolicy)
        self.IPLine.setMinimumSize(QtCore.QSize(200, 0))
        self.IPLine.setInputMask("")
        self.IPLine.setMaxLength(32767)
        self.IPLine.setFrame(True)
        self.IPLine.setObjectName("IPLine")
        self.horizontalLayout.addWidget(self.IPLine)
        self.PortLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PortLine.sizePolicy().hasHeightForWidth())
        self.PortLine.setSizePolicy(sizePolicy)
        self.PortLine.setMaxLength(5)
        self.PortLine.setObjectName("PortLine")
        self.horizontalLayout.addWidget(self.PortLine)
        self.InfoLabel = QtWidgets.QLabel(Dialog)
        self.InfoLabel.setGeometry(QtCore.QRect(10, 250, 651, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoLabel.sizePolicy().hasHeightForWidth())
        self.InfoLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.InfoLabel.setFont(font)
        self.InfoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InfoLabel.setObjectName("InfoLabel")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(670, 10, 321, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TextBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.TextBrowser.setObjectName("TextBrowser")
        self.verticalLayout_4.addWidget(self.TextBrowser)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SendLine = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.SendLine.setMaximumSize(QtCore.QSize(16777215, 100))
        self.SendLine.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.SendLine.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.SendLine.setMaxLength(1000)
        self.SendLine.setObjectName("SendLine")
        self.horizontalLayout_2.addWidget(self.SendLine)
        self.SendButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.SendButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SendButton.sizePolicy().hasHeightForWidth())
        self.SendButton.setSizePolicy(sizePolicy)
        self.SendButton.setMaximumSize(QtCore.QSize(40, 100))
        self.SendButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.SendButton.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.SendButton.setFlat(False)
        self.SendButton.setObjectName("SendButton")
        self.horizontalLayout_2.addWidget(self.SendButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ConnectButton.setText(_translate("Dialog", "Połącz"))
        self.SettingsButton.setText(_translate("Dialog", "Ustawienia"))
        self.RainbowButton.setText(_translate("Dialog", "Rainbow"))
        self.MoreButton.setText(_translate("Dialog", "Więcej >>"))
        self.LabelR.setText(_translate("Dialog", "R"))
        self.LabelG.setText(_translate("Dialog", "G"))
        self.LabelB.setText(_translate("Dialog", "B"))
        self.LabelH.setText(_translate("Dialog", "H"))
        self.LabelS.setText(_translate("Dialog", "S"))
        self.LabelV.setText(_translate("Dialog", "V"))
        self.LocalColor.setText(_translate("Dialog", "<html><head/><body><p>#000000</p></body></html>"))
        self.IPLine.setText(_translate("Dialog", "127.0.0.1"))
        self.IPLine.setPlaceholderText(_translate("Dialog", "Adres IP"))
        self.PortLine.setText(_translate("Dialog", "10000"))
        self.PortLine.setPlaceholderText(_translate("Dialog", "Port"))
        self.InfoLabel.setText(_translate("Dialog", "GPIO Remote"))
        self.TextBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Witaj</p></body></html>"))
        self.SendLine.setPlaceholderText(_translate("Dialog", "Komenda"))
        self.SendButton.setText(_translate("Dialog", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

